# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-22 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0011_attempt_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='label',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
